spring.application.name=Api

spring.datasource.url=jdbc:mysql://localhost:3306/sipentas_apiNew
spring.datasource.username=root
spring.datasource.password=110407
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

//JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

//SERVER
server.port=8080
server.address=0.0.0.0

//APIKEY
sipentas.api-key=SIPENTAS-APP-FIXED-KEY

